### ISSUE TITLE
Problem in Selection Ground Motions

### ISSUE THREAD

**Issue by shkma** [bakerjw/CS_Selection#27]
I am a user of this program.
I noticed a few issue of the program so I'd like to note here:
   
1. It seems that the URL in the output file that is obtained when "NGA_W1_meta_data" and "simulated ground motions" are used is expired.
   
2. When "NGA_W2_meta_data" is used, sometimes "2008 Wenchuan earthquake" is selected, however, the related acceleration data is not available in PEER NGA-West2 database.
    
Regarding comment 2. above, if the program has an option to exclude specified ground motions (by RSN), it may be helpful for users to avoid selecting unavailable data.

**Comment by bakerjw** [comment]
Good comments. These both relate to limitations in what data PEER is currently providing. I'll note these limitations on the ReadMe
