### ISSUE TITLE
Simulate_spectra: Problem in initial seed for simulation when use 'shuffle' in rng function

### ISSUE THREAD

**Issue by cafariza** [bakerjw/CS_Selection#29]
Hi!
I just found an error while using 'shuffle' in the control number random generator (rng) (simulate_spectra function). I changed it by rng('default') instead, and now the code runs. 
According to rng [documentation](https://fr.mathworks.com/help/matlab/ref/rng.html#:~:text=rng(%20seed%20)%20specifies%20the%20seed,a%20sequence%20of%20random%20numbers.), it is not recommended to use 'shuffle' when parallel processing is performed. It is better to use 'default'. This could be my case. 
Here is what I modified
 `% Set initial seed for simulation

if seedValue ~= 0
    rng(seedValue); 
else
    rng('default');
end`

**Comment by bakerjw** [comment]
Sounds good--I updated the code as suggested. Thanks!
